### ISSUE TITLE
FriendlyId 5.0.0 doesn't appear to work as expected with Rails 4.2.5 and Ruby 2.0.0

### ISSUE THREAD

**Issue by bytenel** [norman/friendly_id#715] opened 2015-12-02 17:20 UTC
When listing a model with FriendlyId and the finders extension enabled my test suite fails after upgrading my version of Rails. It seems that the behavior to overwrite the finders doesn't seem to work as expected.

My model is setup like so.

```
class Business < ActiveRecord::Base
  # Gems
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end
```

And the code that calls the find method (line 59 of the businesses_controller) is:

```
def show
    @business = Business.find(params[:id])
 end
```

The stack trace for one of my failed test is as follows.
```
 4) Businesses with the selenium test harness staff can delete a business
     Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::RecordNotFound:
       Couldn't find Business with 'id'=dach-torp-and-schuppe
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5/lib/active_record/core.rb:155:in `find'
     # ./app/controllers/businesses_controller.rb:59:in `show'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:198:in `process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:137:in `process'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionview-4.2.5/lib/action_view/rendering.rb:30:in `process'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal.rb:196:in `dispatch'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_controller/metal.rb:237:in `block in action'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:45:in `serve'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/flash.rb:260:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5/lib/active_record/query_cache.rb:36:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/airbrake-4.1.0/lib/airbrake/rails/middleware.rb:13:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/quiet_assets-1.0.3/lib/quiet_assets.rb:23:in `call_with_quiet_assets'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/capybara-2.5.0/lib/capybara/server.rb:19:in `call'
     # /Users/bytenel/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
```

After changing the controller to:
```
  def show
    @business = Business.friendly.find(params[:id])
  end
```

The test passes so I think it's something in FriendlyId not behaving as advertised.

**Comment by kimrgrey** [comment] 2015-12-17 21:10
Hi, @bytenel! 

Thank you for your feedback! Could you please provide a runnable self-contained snippet of code that can reproduce your problem? Use following code as an example:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.5'
  gem 'sqlite3'
  gem 'friendly_id', '~> 5.1.0', :require => false
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'friendly_id'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.string :title
    t.string :slug
  end

  create_table :friendly_id_slugs do |t|
    t.string   :slug,           :null => false
    t.integer  :sluggable_id,   :null => false
    t.string   :sluggable_type, :limit => 50
    t.string   :scope
    t.datetime :created_at
  end

  add_index :friendly_id_slugs, :sluggable_id
  add_index :friendly_id_slugs, [:slug, :sluggable_type], length: { slug: 140, sluggable_type: 50 }
  add_index :friendly_id_slugs, [:slug, :sluggable_type, :scope], length: { slug: 70, sluggable_type: 50, scope: 70 }, unique: true
  add_index :friendly_id_slugs, :sluggable_type
end

FriendlyId.defaults do |config|
end

class Post < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: "Test")
    assert_equal post, Post.find("test") # it works well on Ruby 2.0.0
  end
end
```

I've launched it on Ruby 2.0.0 and everything works fine:

![screen shot 2015-12-18 at 00 04 35](https://cloud.githubusercontent.com/assets/855918/11882084/9174d978-a51b-11e5-9e2a-f418a4906caf.png)

**Comment by bytenel** [comment] 2015-12-28 16:53
Thanks for the follow up! I'll take a look later tonight and post a response with code. It's on some closed source material so I have to do a little bit of fiddling on my own before making a response.

**Comment by kimrgrey** [comment] 2015-12-30 17:22
@bytenel, hey! Any news about this bug? I'm really ready to solve the problem, but may be it's not a friendly_id problem? Or it occurs some other way?

**Comment by kimrgrey** [comment] 2016-01-02 09:26
Well, I will close this issue because it looks like problem was not in friendly_id or it was fixed in latest versions. Anyway, @bytenel, I'll be glad to re-open this issue if you find additional details that allows to re-produce a problem. Thank you for your participation!

**Closed by kimrgrey** 2016-01-02 09:26 UTC
